version: 2.1

parameters:
  gio_action:
    type: enum
    enum: [release, pull_requests]
    default: pull_requests
  dry_run:
    type: boolean
    default: true
    description: "Run in dry run mode?"
  maven_profile_id:
    type: string
    default: "gravitee-dry-run"
    description: "Maven ID of the Maven profile to use for a dry run ?"
  secrethub_org:
    type: string
    default: "graviteeio"
    description: "SecretHub Org to use to fetch secrets ?"
  secrethub_repo:
    type: string
    default: "cicd"
    description: "SecretHub Repo to use to fetch secrets ?"
  next_snapshot_version:
    type: string
    default: ''
    description: "Used only for the Gravitee Parent Release Process: What will be the next snapshot version?"

orbs:
  slack: circleci/slack@4.8.2
  gravitee: gravitee-io/gravitee@1.0.46

workflows:
  version: 2.1
  # -- typically this workflow is executed on pull requests events for Community Edition Gravitee Repositories
  pull_requests:
    when:
      and:
        - equal: [ pull_requests, << pipeline.parameters.gio_action >> ]
    jobs:
      - gravitee/d_pull_requests_secrets:
          context: cicd-orchestrator
          name: pr_secrets_resolution
      - gravitee/d_pr_tests_containers_qa:
          context: gravitee-qa
          name: process_pull_request_qa
          requires:
            - pr_secrets_resolution
          # "What is the maven ID of the maven profile to use to build and deploy SNAPSHOTS to Prviate Artifactory ?"
          maven_profile_id: 'gio-dev'
          filters:
            branches:
              ignore:
                - master
      - gravitee/d_pull_requests_ce:
          name: process_pull_request
          requires:
            - pr_secrets_resolution
          # "What is the maven ID of the maven profile to use to build and deploy SNAPSHOTS to Prviate Artifactory ?"
          maven_profile_id: 'gio-dev'
          # nexus_snapshots_url: 'https://oss.sonatype.org/content/repositories/snapshots'
          # nexus_snapshots_server_id: 'sonatype-nexus-snapshots'
          # container_gun_image_org: 'circleci'
          # container_gun_image_name: 'openjdk'
          # container_gun_image_tag: '11.0.3-jdk-stretch'
          container_size: 'medium'
          # filters:
            # branches:
              # ignore:
                # - master

  release:
    when:
      and:
        - equal: [ release, << pipeline.parameters.gio_action >> ]
        - not : << pipeline.parameters.dry_run >>
    jobs:
      - gravitee/d_gio_bom_release_secrets:
          context: cicd-orchestrator
          name: 'gio_parent_release_secrets'
      - gravitee/d_gio_bom_release:
          requires:
            - gio_parent_release_secrets
          dry_run: << pipeline.parameters.dry_run >>
          maven_profile_id: 'gio-release'
          next_snapshot_version: << pipeline.parameters.next_snapshot_version >>

  release_dry_run:
    when:
      and:
        - equal: [ release, << pipeline.parameters.gio_action >> ]
        - << pipeline.parameters.dry_run >>
    jobs:
      - gravitee/d_gio_bom_release_secrets:
          context: cicd-orchestrator
          name: 'gio_parent_release_secrets'
      - gravitee/d_gio_bom_release:
          requires:
            - gio_parent_release_secrets
          dry_run: << pipeline.parameters.dry_run >>
          maven_profile_id: 'gravitee-dry-run'
          next_snapshot_version: << pipeline.parameters.next_snapshot_version >>
